config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :legislators, only: [:index] do
    collection do
      get 'diputados'
      get 'senadores'
      get 'search'
    end
  end

  resources :comissions, only: [:index, :show] do
    collection do
      get 'diputados'
      get 'senadores'
    end
  end

  resources :sessions, only: [:index, :show] do
    collection do
      get 'diputados'
      get 'senadores'
    end
  end
end

app/views/shared/_calendar_data.html.erb
<script>
    var codropsEvents = { };
    <% @sessions.each do |session| %>
        codropsEvents['<%= session.date.strftime('%m-%d-%Y') %>']
                = '<%= link_to 'Ver detalles', session_path(session) %>';
    <% end %>
</script>

app/views/shared/_footer.html.erb
<!-- #### FOOTER #### -->
<div class="row large-12 columns text-right footer">
  <p><strong>Ágora es un proyecto desarrollado por:</strong></p>
  <p>Virginia Rodríguez, Ignacio Gentini y Sebastián Beltrán</p>
</div>

app/views/shared/_legislator_data.html.erb
<% if legislator %>
<div class="large-4 medium-6 small-12 columns mix <%= legislator.political_party.name.gsub(' ', '_') %>" data-myorder="<%= legislator.attendance %>">
  <div class="ficha">
    <div class="bandera_derecha right"><%= image_tag right_flag_image(legislator.political_party.name) %></div>
    <div class="row ficha-parlamentario">
      <!-- #### FOTO PERFIL ####-->
      <div class="small-4 columns">
        <%= image_tag legislator.picture_url, class: 'foto_perfil' %>
      </div>
      <!-- #### NOMBRE E ICONOS ####-->
      <div class="small-8 columns end datos-parlamentario">
      <!-- #### NOMBRE ####-->
      <div class="row"><h4 class="nombre"><%= legislator.full_name.titleize %></h4></div>
      <!-- #### DEPARTAMENTO ####-->
      <div class="row">
        <p class="deptos"><%= legislator.chamber_and_state_info.upcase %></p>
      </div>
      <!-- #### ICONOS ####-->
      <div class="row iconos">
        <!-- #### EXPERTISE ####-->
        <div class="small-8 columns margen-derecho">
            <ul>
              <% legislator.expertise.each do |topic| %>
                  <li><%= image_tag "icono_#{topic}.svg", class: 'iconos-expertise', title: topic.titleize %></li>
              <% end %>
          </ul>
        </div>
         <!-- #### CONTACTO ####-->
        <div class="small-4 columns margen-derecho">
            <ul>
                <li><a href="<%= "mailto:#{legislator.email}" %>"><%= image_tag 'icono_correo.svg', class: 'icono-correo' %></a></li>
                <li><a href="http://facebook.com " target="_blank"><%= image_tag 'icono_fb.svg', class: 'icono-fb' %></a></li>
                <li><a href="http://twitter.com" target="_blank"><%= image_tag 'icono_tw.svg', class: 'icono-tw' %></a></li>
            </ul>
        </div>
      </div>
    </div>
   </div>
    <!-- #### 1RA LINEA DE DATOS ####-->
    <div class="row">
        <div class="small-4 columns">
          <p class="valor-parlamentario-arriba"><%= legislator.attendance %>%</p>
        </div>
        <div class="small-4 columns">
          <p class="valor-parlamentario-arriba">-</p>
        </div>
        <div class="small-4 columns">
          <p class="valor-parlamentario-arriba">-</p>
        </div>
    </div>
    <!-- #### 2DA LINEA DE DATOS ####-->
    <div class="row">
        <div class="small-4 columns">
          <p class="dato-ficha">asistencia</p>
        </div>
        <div class="small-4 columns">
          <p class="dato-ficha">iniciativas</p>
        </div>
        <div class="small-4 columns">
          <p class="dato-ficha">intervenciones</p>
        </div>
    </div>
    <!-- #### 3RA LINEA DE DATOS ####-->
    <div class="row">
        <div class="small-4 columns">
          <p class="valor-parlamentario-abajo">$<%= legislator.salary %></p>
        </div>
        <div class="small-4 columns">
          <p class="valor-parlamentario-abajo">-</p>
        </div>
        <div class="small-4 columns">
          <p class="valor-parlamentario-abajo">-</p>
        </div>
    </div>
    <!-- #### 4TA LINEA DE DATOS ####-->
    <div class="row">
        <div class="small-4 columns">
          <p class="dato-ficha">sueldo</p>
        </div>
        <div class="small-4 columns">
          <p class="dato-ficha">períodos</p>
        </div>
        <div class="small-4 columns ultimo-dato">
          <p class="dato-ficha">viajes</p>
        </div>
    </div>
  </div>
</div>
<% else %>
  <div class="large-4 medium-6 small-12 columns"></div>
<% end %>

app/views/shared/_legislators_list.html.erb
<div class="small-12 columns fichas">
  <%= legislators.each_slice(3) do |legislators_row| %>
      <div clas="row">
        <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[0] }  %>
        <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[1] }  %>
        <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[2] }  %>
      </div>
  <% end %>
</div>

app/views/shared/_menu.html.erb
<!-- #### MENU #### -->
<div class="small-12 cabezal">
    <div class="large-4 columns title-area">
      <%= image_tag 'logo.png', alt:"Logo Ágora"%>
    </div>
    <div class="large-7 columns large-offset-1 menu-centrado text-right">
      <ul class="button-group menu">
        <li><%= link_to 'inicio', root_path, class: class_for_menu_link('home', controller_name) %></li>
        <li><%= link_to 'parlamento', legislators_path, class: class_for_menu_link('legislators', controller_name) %></li>
        <li><%= link_to 'agenda', sessions_path, class: class_for_menu_link('sessions', controller_name) %></li>
        <li><%= link_to 'comisiones', comissions_path, class: class_for_menu_link('comissions', controller_name) %></li>
        <li><a href="#"><%= image_tag 'lupa.png', id: "search_button" %><input title="Buscar legislador" id="search" name="query" type="text" placeholder="buscar" value="<%= params[:query] %>"></a></li>
        <li></li>
      </ul>
    </div>
</div>