config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :legislators, only: [:index] do
    collection do
      get 'diputados'
      get 'senadores'
      get 'search'
    end
  end

  resources :comissions, only: [:index, :show] do
    collection do
      get 'diputados'
      get 'senadores'
    end
  end

  resources :sessions, only: [:index, :show] do
    collection do
      get 'diputados'
      get 'senadores'
    end
  end
end

app/models/comission.rb
class Comission < ActiveRecord::Base
  has_many :comission_participants
  has_many :legislators, through: :comission_participants

  CHAMBERS = { diputados: 'D', senadores: 'S', asamblea_general: 'A' }

  scope :of_diputados, -> { where(chamber: CHAMBERS[:diputados]) }
  scope :of_senadores, -> { where(chamber: CHAMBERS[:senadores]) }
  scope :of_asamblea_general, -> { where(chamber: CHAMBERS[:asamblea_general]) }
  scope :by_name, -> { order('name ASC') }

  def categories
    case name.downcase
      when 'educacion y cultura', 'educación y cultura' then ['cultura', 'educacion']
      when 'asuntos laborales y seguridad social' then ['trabajo', 'sociales']
      when 'medio ambiente' then ['medio_ambiente']
      when 'industria' then ['industria']
      when 'salud pública' then ['salud']
      when 'salud publica y asistencia social' then ['salud', 'sociales']
      when 'vivienda y ordenamiento territorial', 'vivienda' then ['vivienda']
      when 'asuntos internacionales' then ['internacional']
      when 'defensa nacional' then ['defensa']
      when 'transporte y obras públicas' then ['transporte']
      when 'presupuesto', 'presupuestos', 'hacienda', 'hacienda y presupuesto' then ['economia']
      when 'derechos humanos', /poblaci.n/, 'derechos humanos y peticiones', 'seguridad social' then ['sociales']
      when 'transporte' then ['transporte']
      when 'turismo' then ['turismo']
      when 'legislacion del trabajo' then ['trabajo']
      when /deporte/ then ['deporte']
      when /genero y equidad/ then ['sociales']
      else ['otros']
    end
  end

end

app/controllers/comissions_controller.rb
class ComissionsController < ApplicationController

  def index
    @comissions = Comission.of_asamblea_general.by_name
    filter_by_type

    @selected_chamber = 'A'
    @action = 'index'
  end

  def senadores
    @comissions = Comission.of_senadores.by_name
    filter_by_type

    @selected_chamber = 'S'
    @action = 'senadores'

    render :index
  end

  def diputados
    @comissions = Comission.of_diputados.by_name

    filter_by_type

    @selected_chamber = 'D'
    @action = 'diputados'

    render :index
  end

  def show
    @comission = Comission.find(params[:id])
    @selected_chamber = @comission.chamber

    if @comission.chamber == Comission::CHAMBERS[:diputados]
      @comissions = Comission.of_diputados.by_name
      @action = 'diputados'
    elsif@comission.chamber == Comission::CHAMBERS[:senadores]
      @comissions = Comission.of_senadores.by_name
      @action = 'senadores'
    else
      @comissions = Comission.of_asamblea_general.by_name
      @action = 'index'
    end

    filter_by_type
  end

  private

  def filter_by_type
    @comissions = @comissions.where(comission_type: params[:type]) if params[:type].present? && params[:type] != 'todas'
  end

end

app/views/comissions/_comissions_list.html.erb
<% current_comission ||= 0 %>

<div class="small-12 columns camara">
  <div class="large-5 large-offset-6">
    <hr>
    <div class="button-group ">
      <%= render partial: 'filters_by_chamber' %>
    </div>
  </div>
</div>
<div class="small-12 columns text-right">
  <div class="small-8 small-offset-3 ">
    <%= render partial: 'filter_by_type' %>
  </div>
</div>

<!-- #### COMISIONES #### -->
<div class="row comisiones margen-superior">
  <% first_column = true %>
  <% slice_size = comissions.size / 2 %>
  <% slice_size += 1 if (comissions.size % 2) != 0 %>
  <% comissions.each_slice(slice_size) do |comission_list|%>
      <% div_class = first_column ? 'large-5 large-offset-1 columns' : 'large-5 end columns' %>
      <div class="<%= div_class %>">
        <ul class="no-bullet">
          <% comission_list.each do |comission| %>
              <% link_class = current_comission == comission.id ? 'active' : '' %>
              <li><%= link_to pretty_text(comission.name), comission_path(comission, type: params[:type]), class: link_class %></li>
          <% end %>
        </ul>
      </div>

      <% first_column = false %>
  <% end %>
</div>

app/views/comissions/_filter_by_type.html.erb
<% current_type = params[:type] || 'todas' %>
<div class="filtro">
  <ul class="right">
    <li class="<%= class_for_filter('todas', current_type) %>">
      <%= link_to 'todas', controller: 'comissions', action: @action, type: 'todas' %>
    </li>

    <li class="<%= class_for_filter('P', current_type) %>">
      <%= link_to 'comisiones permantentes', controller: 'comissions', action: @action, type: 'P' %>
    </li>
    <li class="<%= class_for_filter('E', current_type) %>">
      <%= link_to 'comisiones especiales', controller: 'comissions', action: @action, type: 'E' %>
    </li>
  </ul>
</div>

app/views/comissions/_filters_by_chamber.html.erb
<ul class="right">
  <li><%= link_to 'asamblea general', comissions_path, class: class_for_submenu_link('A', @selected_chamber) %></li>
  <li><%= link_to 'senadores', senadores_comissions_path, class: class_for_submenu_link('S', @selected_chamber) %></li>
  <li><%= link_to 'diputados', diputados_comissions_path, class: class_for_submenu_link('D', @selected_chamber) %></li>
<ul>

app/views/comissions/index.html.erb
<%= render partial: 'comissions_list', locals: { comissions: @comissions } %>

app/views/comissions/show.html.erb
<%= render partial: 'comissions_list', locals: { comissions: @comissions, current_comission: @comission.id } %>

<% if @comission.legislators.any? %>
    <%= render partial: 'shared/legislators_list', locals: { legislators: @comission.legislators } %>
<% else %>
    <div class="small-12 columns fichas">
      <div class="row">
        <div class="large-12 columns ficha">
          <p class="no_data">Comisión pendiente de integración a la fecha de consulta</p>
        </div>
      </div>

    </div>

<% end %>