config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :legislators, only: [:index] do
    collection do
      get 'diputados'
      get 'senadores'
      get 'search'
    end
  end

  resources :comissions, only: [:index, :show] do
    collection do
      get 'diputados'
      get 'senadores'
    end
  end

  resources :sessions, only: [:index, :show] do
    collection do
      get 'diputados'
      get 'senadores'
    end
  end
end

app/models/legislator.rb
class Legislator < ActiveRecord::Base
  CHAMBERS = { diputados: 'D', senadores: 'S' }

  has_many :comission_participants
  has_many :comissions, through: :comission_participants

  belongs_to :political_party

  scope :in_diputados, -> { where(chamber: CHAMBERS[:diputados]) }
  scope :in_senadores, -> { where(chamber: CHAMBERS[:senadores]) }
  scope :by_last_name, -> { order('last_name ASC')}

  def full_name
    "#{first_name} #{last_name}"
  end

  def chamber_and_state_info
    if chamber == CHAMBERS[:diputados]
      "Diputado por #{state}"
    else
      is_president ? 'Presidente Senadores y A.General' : "Senador"
    end
  end

  def expertise
    all_topics = comissions.map(&:categories).flatten

    topics_temp = all_topics.reject{|topic| topic == 'otros' }
    topics_count = topics_temp.
        each_with_object(Hash.new(0)) { |topic,counts| counts[topic] += 1 }.
        sort_by{|topic, value| -value }

    topics = topics_count.map{|topic, _| topic }
    if topics.size >= 4
      topics[0..3]
    else
      topics += ['otros'] if all_topics.include?('otros')
      topics
    end
  end

  def attendance
    attendances_count * 100 / citations_count
  end

  def salary
    is_president ? '246.368' : '147.838'
  end

  def self.search_by_name(query)
    Legislator.where("first_name like :query OR last_name like :query", query: "%#{query}%")
  end
end

app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController

  def index
    @legislators = Legislator.by_last_name
  end

  def diputados
    @legislators = Legislator.in_diputados.by_last_name
    render :index
  end

  def senadores
    @legislators = Legislator.in_senadores.by_last_name
    render :index
  end

  def search
    query = params[:query]
    @legislators = Legislator.search_by_name(query).by_last_name
  end

end

app/views/legislators/_filters_by_chamber.html.erb
<ul class="right">
  <li><%= link_to 'asamblea general', legislators_path, class: class_for_submenu_link('index', action_name) %></li>
  <li><%= link_to 'senadores', senadores_legislators_path, class: class_for_submenu_link('senadores', action_name) %></li>
  <li><%= link_to 'diputados', diputados_legislators_path, class: class_for_submenu_link('diputados', action_name) %></li>
<ul>

app/views/legislators/_other_filters.html.erb
<div class="filtro">
  <ul class="right">
    <span>orden:</span>
    <li class="label margen-izquierda-mitad sort active" data-sort="default:asc">alfabético</li>
    <li class="label margen-izquierda-mitad sort" data-sort="myorder:desc">por mayor asistencia</li>
    <li class="label margen-izquierda-mitad sort" data-sort="myorder:asc">por menor asistencia</li>
    <span style="margin-left: 20px;">filtros:</span>
    <li class="label margen-izquierda-mitad filter" data-filter="all">todos</li>
    <li class="label margen-izquierda-mitad filter" data-filter=".partido_nacional">p.nacional</li>
    <li class="label margen-izquierda-mitad filter" data-filter=".partido_colorado">p.colorado</li>
    <li class="label margen-izquierda-mitad filter" data-filter=".partido_frente_amplio">frente amplio</li>
    <li class="label margen-izquierda-mitad filter" data-filter=".partido_independiente">p.independiente</li>
    <ul>
</div>

app/views/legislators/index.html.erb
<div class="small-12 columns camara">
  <div class="large-5 large-offset-6">
    <hr>
    <div class="button-group ">
        <%= render partial: 'filters_by_chamber' %>
    </div>
  </div>
</div>
<div class="small-12 columns text-right">
  <div class="small-9 small-offset-2 ">
    <%= render partial: 'other_filters' %>
  </div>
</div>

<!-- #### FICHAS DE PARLAMENTOS #### -->
<div class="small-12 columns fichas">

<%= @legislators.each_slice(3) do |legislators_row| %>
    <div clas="row">
      <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[0] }  %>
      <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[1] }  %>
      <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[2] }  %>
    </div>
<% end %>


</div>

app/views/legislators/search.html.erb
<% if @legislators.any? %>
    <div class="small-12 columns fichas">
      <%= @legislators.each_slice(3) do |legislators_row| %>
          <div clas="row">
            <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[0] }  %>
            <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[1] }  %>
            <%= render partial: 'shared/legislator_data', locals: { legislator: legislators_row[2] }  %>
          </div>
      <% end %>
    </div>
<% else %>
    <div class="small-12 columns fichas">
      <div class="row">
        <div class="large-12 columns ficha">
          <p class="no_data">No se encontraron resultados.</p>
        </div>
      </div>

    </div>
<% end %>